name: OreoandTiger
favicon: null
layout_spectrum: 0.12465
typography_spectrum: 0.15405
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#b98e49'
    - '#915d07'
    - '#592300'
    - '#d22a00'
  brandStrength: 0.708490239456296
  lightness: 0.8125
  saturation: 0.737525834934786
  rhythmicContrast: 0.5
purpose: []
