name: OreoandTiger
favicon: null
layout_spectrum: 0.12465
typography_spectrum: 0.15405
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#b98e49'
    - '#915d07'
    - '#592300'
    - '#d22a00'
  brandStrength: 0.5
  lightness: 0.9375
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
