name: OreoandTiger
favicon: null
layout_spectrum: 0.12465
typography_spectrum: 0.15405
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#dac8a4'
    - '#543b0a'
    - '#fffffa'
    - '#ad9356'
    - '#000004'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
