name: OreoandTiger
favicon: null
layout_spectrum: 0.727536452235654
typography_spectrum: 0.4451782170217484
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.708490239456296
  lightness: 0.03192638512700796
  saturation: 0.737525834934786
  rhythmicContrast: 0.4639171555172652
purpose: []
